Allow for spaces in column names from source system
SAP/sap-commerce-db-sync pull request #15
Opened 2024-03-06 09:38 UTC by jamiebartlett-kps

2024-03-06 12:58 UTC, lnowakowski commented on commercedbsync/src/com/sap/cx/boosters/commercedbsync/repository/platform/MigrationHybrisMSSqlPlatform.java
> +    private static final String[] KNOWN_SYSTEM_TABLES = new String[]{"dtproperties"};
DB Sync is designed to handle only SAP Commerce type system tables, custom tables should be handled by `migration.data.tables.custom` property. Any particular reason for such customization to be hardcoded here?

2024-03-21 06:36 UTC, lnowakowski requested changes

2024-03-21 06:36 UTC, lnowakowski commented on commercedbsync/src/com/sap/cx/boosters/commercedbsync/repository/platform/MigrationHybrisMSSqlPlatform.java
> +        protected void determineAutoIncrementFromResultSetMetaData(Table table, Column[] columnsToCheck) throws SQLException {
What is the purpose of this method? SAP Commerce is not utilizing MSSQL autoincrement (`IDENTITY`) functionality.

2024-03-21 06:36 UTC, lnowakowski commented on commercedbsync/src/com/sap/cx/boosters/commercedbsync/repository/platform/MigrationHybrisMSSqlPlatform.java
> +    private static final String[] KNOWN_SYSTEM_TABLES = new String[]{"dtproperties"};
If this is related with Database Diagrams used in older versions of MSSQL, there is no intent to handle such in core functionality of DB Sync

2024-03-21 08:11 UTC, jamiebartlett-kps commented
Hi @lnowakowski 

Thanks for your comments. In the PR, the only change is actually only the below snippet:

 ```if (this.getPlatform().isDelimitedIdentifierModeOn()) {
    query.append(this.getPlatformInfo().getDelimiterToken());
}

query.append(table.getName());
if (this.getPlatform().isDelimitedIdentifierModeOn()) {
    query.append(this.getPlatformInfo().getDelimiterToken());
}```

To add the delimiter tokens around the outside of the table name after the FROM in the query. The rest of the changes were necessary as the method which required changing was protected inside the Apache DDLUtils Library.

2024-03-21 09:24 UTC, lnowakowski commented
Thanks for response @jamiebartlett-kps , can you elaborate a bit more, how common in your case is that SAP Commerce type system attribute has space char in its name? IMO it's not verry often, nor maybe it's not even following general recommendations or naming conventions for DB columns

2024-03-21 09:26 UTC, jamiebartlett-kps commented
Agreed that it's uncommon in the source system, but if you're replicating into a target system which isn't empty and also holds tables from other sources, it's possible. This is our use case and we've resolved the issue using this change.

2024-03-21 09:37 UTC, lnowakowski commented
> Agreed that it's uncommon in the source system, but if you're replicating into a target system which isn't empty and also holds tables from other sources, it's possible. This is our use case and we've resolved the issue using this change.

Understood, however if you're not migrating data to such table, I'd recommend to exclude it, if exclusions feature is not handling this, during either schema analysis or migration process, it's a different story that should be handled as a bug

2024-07-09 06:53 UTC, closed without merging